backend_task:
  description: >
    Analyze backend technologies, libraries, and frameworks from the provided Technology Radar document.
    Focus on .NET and Python ecosystems mentioned in the document. For each technology:
    1. Analyze current adoption levels in the industry
    2. Specify whether it's open-source or licensed
    3. Provide insights on why certain technologies are in their respective quadrants (Adopt, Trial, Assess, Hold)
    4. Highlight any technologies that should be moved to different quadrants based on current industry trends
  expected_output: >
    A comprehensive analysis of backend technologies with focus on adoption trends, licensing models, and recommendations for quadrant changes.
  agent: backend_expert

frontend_task:
  description: >
    Analyze frontend technologies, libraries, and frameworks from the provided Technology Radar document.
    Focus on Angular ecosystem and other frontend technologies mentioned in the document. For each technology:
    1. Analyze current adoption levels in the industry
    2. Specify whether it's open-source or licensed
    3. Provide insights on why certain technologies are in their respective quadrants (Adopt, Trial, Assess, Hold)
    4. Highlight any technologies that should be moved to different quadrants based on current industry trends
  expected_output: >
    A comprehensive analysis of frontend technologies with focus on adoption trends, licensing models, and recommendations for quadrant changes.
  agent: frontend_expert

testing_task:
  description: >
    Analyze testing frameworks, libraries, and tools from the provided Technology Radar document.
    Focus on testing technologies across multiple platforms. For each technology:
    1. Analyze current adoption levels in the industry
    2. Specify whether it's open-source or licensed
    3. Provide insights on why certain technologies are in their respective quadrants (Adopt, Trial, Assess, Hold)
    4. Highlight any technologies that should be moved to different quadrants based on current industry trends
  expected_output: >
    A comprehensive analysis of testing technologies with focus on adoption trends, licensing models, and recommendations for quadrant changes.
  agent: testing_expert

coordinator_task:
  description: >
    Review and synthesize the analyses from the Backend, Frontend, and Testing experts.
    Create a comprehensive technology radar summary that highlights:
    1. Cross-cutting trends and patterns across all domains
    2. Consolidated list of technologies that should change quadrants
    3. Licensing model insights across the technology landscape
    4. Recommendations for technology adoption strategy
  expected_output: >
    A comprehensive technology radar summary with cross-domain insights and strategic recommendations.
  agent: coordinator
  dependencies:
    - backend_task
    - frontend_task
    - testing_task
